# Generated by Django 6.1 on 2026-08-23 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a3_app', '0002_contact_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='Auto-generated reference, e.g. A3-0001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GST / Tax Number')),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Scope of work / requirement details')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('negotiating', 'Negotiating'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('project_url', models.URLField(blank=True, help_text='Live site / delivered project link')),
                ('domain_name', models.CharField(blank=True, max_length=255)),
                ('hosting_provider', models.CharField(blank=True, max_length=255)),
                ('domain_expiry_date', models.DateField(blank=True, null=True)),
                ('hosting_expiry_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount originally quoted', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, help_text='Agreed amount after discount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('advance_paid', 'Advance Paid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. 50% advance, 50% on delivery', max_length=255)),
                ('price_detail', models.TextField(blank=True, help_text='Itemised price breakdown / notes')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('proposed_on', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('completion_target_date', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Handed over to the client', null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='AMC / maintenance renewal', null=True)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='clients/quotations/', verbose_name='Quotation (image / PDF)')),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='clients/agreements/')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='clients/invoices/')),
                ('source', models.CharField(blank=True, help_text='How the client reached us — referral, Instagram, walk-in, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not shown to the client')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, help_text='Inquiry this client came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='a3_app.inquiry')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='a3_app.service')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
